# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: O:/CS56_S23/vga_midi/vga_midi/vga_midi.srcs/sources_1/ip/blk_pix_booleans/blk_pix_booleans.xci
# IP: The module: 'blk_pix_booleans' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/CS56_S23/vga_midi/vga_midi/vga_midi.gen/sources_1/ip/blk_pix_booleans/blk_pix_booleans_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_pix_booleans'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: O:/CS56_S23/vga_midi/vga_midi/vga_midi.srcs/sources_1/ip/blk_pix_booleans/blk_pix_booleans.xci
# IP: The module: 'blk_pix_booleans' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/CS56_S23/vga_midi/vga_midi/vga_midi.gen/sources_1/ip/blk_pix_booleans/blk_pix_booleans_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_pix_booleans'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
