@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jun 05 22:50:59 -0400 2023
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim vga_test_pattern_shell_tb_behav -key {Behavioral:sim_1:Functional:vga_test_pattern_shell_tb} -tclbatch vga_test_pattern_shell_tb.tcl -view O:/CS56_S23/vga_midi/vga_midi/vga_test_pattern_shell_tb_behav.wcfg -log simulate.log"
call xsim  vga_test_pattern_shell_tb_behav -key {Behavioral:sim_1:Functional:vga_test_pattern_shell_tb} -tclbatch vga_test_pattern_shell_tb.tcl -view O:/CS56_S23/vga_midi/vga_midi/vga_test_pattern_shell_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
